### ISSUE TITLE
Importing ABC directly from collections is deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [man-group/pytest-plugins#157]
https://github.com/man-group/pytest-plugins/blob/b798cc203c588e030c4e0518b65925ccfa961de5/pytest-verbose-parametrize/pytest_verbose_parametrize.py#L1

**Comment by mafalb** [comment]
the upcoming fedora 35 comes with python 3.10 and throws an exception already

```
$ docker run --rm -ti fedora:35
[root@9d4376861e47 /]# python3 --version
Python 3.10.0b4
[root@9d4376861e47 /]# python3 -m venv /root/pytest
[root@9d4376861e47 /]# . /root/pytest/bin/activate
(pytest) [root@9d4376861e47 /]# pip install pytest-verbose-parametrize
Collecting pytest-verbose-parametrize
  Downloading pytest_verbose_parametrize-1.7.0-py2.py3-none-any.whl (6.7 kB)
Collecting pytest
  Downloading pytest-6.2.4-py3-none-any.whl (280 kB)
     |████████████████████████████████| 280 kB 2.6 MB/s 
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting attrs>=19.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 1.9 MB/s 
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pluggy<1.0.0a1,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.8.2
  Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 4.6 MB/s 
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting packaging
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 5.4 MB/s 
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 3.8 MB/s 
Installing collected packages: pyparsing, toml, py, pluggy, packaging, iniconfig, attrs, six, pytest, pytest-verbose-parametrize
Successfully installed attrs-21.2.0 iniconfig-1.1.1 packaging-21.0 pluggy-0.13.1 py-1.10.0 pyparsing-2.4.7 pytest-6.2.4 pytest-verbose-parametrize-1.7.0 six-1.16.0 toml-0.10.2
WARNING: You are using pip version 21.1.3; however, version 21.2.1 is available.
You should consider upgrading via the '/root/pytest/bin/python3 -m pip install --upgrade pip' command.
(pytest) [root@9d4376861e47 /]# py.test --version
Traceback (most recent call last):
  File "/root/pytest/bin/py.test", line 8, in <module>
    sys.exit(console_main())
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/root/pytest/lib64/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/root/pytest/lib64/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/root/pytest/lib64/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/root/pytest/lib64/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/root/pytest/lib64/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/root/pytest/lib64/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/root/pytest/lib64/python3.10/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/pytest/lib64/python3.10/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/root/pytest/lib64/python3.10/site-packages/pytest_verbose_parametrize.py", line 1, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
```

**Comment by ssbarnea** [comment]
And this finally happened. I guess that is the time to drop using pytest-verbose-parametrize plugin.
